[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Serve r/index.html for all /r/[code] paths
[[redirects]]
  from = "/r/*"
  to   = "/r/index.html"
  status = 200
